imgix/react-imgix

- src/index.js
- src/index.test.js
This adds a new option called `srcSet` which defaults to true. When enabled, the 2x and 3x srcSet attributes will be added to rendered component. Currently, the attribute will only be added if the rendered component is an `img`.
What do you all think? I don't know if the option name is the best at the moment.
> Automatically set srcSet attributes

- src/index.js
adds a separate updateImageState to allow a parent component to trigger an image reload
> expose updateImageState to parent components

- README.md
- src/index.js
- src/index.test.js
The Imgix docs [describes passing multiple options](https://docs.imgix.com/apis/url/size/crop) to the 'crop' parameter, useful for providing fallbacks to the 'faces' crop. This PR enables doing that by exposing the 'crop' param as an optional string parameter. Passing in a specific 'crop' attribute, overrides the 'faces' and 'entropy' flags.
> Enable passing in specific crop options, useful for fallbacks

- src/index.js
- src/index.test.js
Noticed a typo in the deprecation warning for the `bg` prop
> fix typo - deprecated warning

- README.md
- src/index.js
- src/index.test.js
We had to specify some custom background sizing on some components with CSS. This was difficult, because the background size was directly applied to the style.
> Background Size adjustments

- README.md
- src/index.js
- src/index.test.js
This adds the ability to register an `onMounted` callback that will be called with the underlying DOM node as an argument.
This can be useful for a number of reasons, but in our case, it's a workaround for issue https://github.com/imgix/react-imgix/issues/41. This way, we can render the image without the alt tag (which won't affect the size calculation), and append the alt attribute after mounting.
> add onMounted callback with access to underlying node

- package.json
- src/index.js
- src/index.test.js
i tested with 15.5. and 15.4 and this change worked fine - i tried to test with 0.14.x but gave up trying to chase down the required `devDependencies` changes. if this is important we might consider setting up multiple builds to verify older version compatibility.
> pull in prop-types from a separate module, fix sinon deprecation warning

- package.json
fixes the required packages for [skin-deep](https://github.com/glenjamin/skin-deep#install) when using `react 15.5`, updates other `devDependencies`.  should supersede #103 (also fixes react warnings in the build)
> npm updates / changes for skin-deep-1.0.0

- package.json
- src/index.js
- src/index.test.js
- yarn.lock
1. pass `imgProps` down to `<img>` tags auto-generated by `type=picture` - previously this was done as a spread assignment since `className` and `styles` were the only `imgProps` we cared about (and we wanted to set those directly on the newly created `<Imgix>` component rather than its `<img>` child). 
2. strip `alt` props from `<picture>` and `<source`> tags since they're not allowed. 
3. update deps
> fix alt tag handling

- .babelrc
- package-lock.json
- package.json
- src/index.test.js
- yarn.lock
BREAKING CHANGE: Only React v16 supported
only a little bit of cleanup in the tests to get them happy.
> chore(deps): Update all deps, move to react16 for testing

- .babelrc
- .gitignore
- package-lock.json
- package.json
- src/index.test.js
hah, i was really hoping to get this in before you did the 7 bump (this is why i was upgrading deps, i wanted to make that a separate change though).
the only thing that's not 100% is `build:watch` - i don't know an easy pattern to have multiple watch processes running. not sure how much that matters though, i could add a separate `commonjs` and `es` watch task
> chore: add es build

- .babelrc
- README.md
- package-lock.json
- package.json
- src/react-imgix.js
- test/unit/react-imgix.test.js
This PR adds an `ixlib` parameter to urls generated by this component. The url parameter is in the form `ixlib=react-7.1.1`. There are two reasons to add this parameter: a) it helps Imgix support see what versions of libraries that customers are using, and b) it help Imgix to see how many people overall are using the react library, and the specific versions.
This functionality is enabled by default but can be turned off by passing the prop `disableLibraryParam`.
This closes #142.
Either review the unit tests in `test/unit/react-imgix.test.js` or set-up a new app and inspect the generated URLs.
> feat: add ixlib url parameter to help Imgix support and analytics

- .travis.yml
- config/karma/karmaConfig.js
Before this PR, Pull Requests submitted by non-contributors failed on CI because the integration tests failed. This is because Travis does not provide environment variable to outsiders' Pull Requests for safety reasons, and so the tests could not log in to BrowserStack.
This PR updates the CI configuration to run all tests for contributors, and only run integration tests on Chrome and Firefox for community PRs.
This fixes #148 
Steps:
1. Observe that the Travis build passes for this PR, and that all tests are run (including BrowserStack)
2. Remove the `BROWSERSTACK` keys from https://travis-ci.org/imgix/react-imgix/settings
3. Restart the build and observe that only the Chrome and Firefox tests run
4. Ask me to add back the environment variables for Browserstack.
> chore(ci): disable browserstack for community PRs

- README.md
The link to the LICENSE in the readme included an `.md` extension, which the file doesn't have. This PR simply fixes the link.
> chore(readme): fix license link

- config/karma/karmaConfig.js
Builds were flaking on Travis as some integration tests were randomly timing out. This increases the timeout by 10x from 2s to 20s, which should stop these tests from timing out.
> chore(integration-test): increase mocha timeout to try stop tests failing randomly

- README.md
- src/react-imgix.js
- test/unit/react-imgix.test.js
BREAKING CHANGE: A fallback image will no longer be created when using react-imgix in picture mode
The fallback image support when using react-imgix in `picture` mode was causing issues with sizing in #90 as the size being passed to the root `picture` component was being used for the fallback as well. This was causing problems, and the simplest solution was to remove the fallback image creation. This is inline with the HTML spec, so anyone used to using `<picture>` elements in HTML will be at home with this. There is more discussion in #90.
A problem here is that `src` is a required prop for react-imgix, which will cause an error when using `picture` mode as a `src` now isn't going to be passed to the root component. An option we have here is to update the `src` prop to not be required, …
> fix: warn the user when no <img> passed as a child to <picture> fixes #90

- config/karma/karmaConfig.js
- config/karma/karmaConfigHeadlessCI.js
- package.json
Previously iOS was not able to be tested on BrowserStack due to issues with the interaction with BrowserStack. This has now been fixed so iOS support can be re-enabled.
Check that the Travis CI log is testing iOS ("mobile safari")
Can be see above as `bs_ios_saf_iPhone 8_11.0`
> chore(integration-test): add ios integration test support

- README.md
This PR fixes a typo in README and fixes a problem with the CodeSandbox examples. GitHub does not allow rendering `iframe` elements in the README, so the iframes were converted to links.
> chore(readme): fix typo and update codesandbox examples

- README.md
- src/HOCs/deprecatePropsHOC.js
- src/HOCs/index.js
- src/HOCs/shouldComponentUpdateHOC.js
- src/common.js
- src/index.js
- src/react-imgix.js
- test/integration/react-imgix.test.js
- test/unit/helpers/shallowUntilTarget.test.js
- test/unit/react-imgix.test.js
BREAKING CHANGES: - picture and source types have been changed to components. 
**NB: This is currently a stacked PR. I will change the base to `version-8` when #162 is resolved. The last commit in the PR moved some stuff around, it may help to view [this diff](https://github.com/imgix/react-imgix/pull/163/files/0b88acb3f646691ef1df80b207b5e09935df54f5) first to see the feature changes.**
This PR builds on the changes described in #144. Having the picture and source behaviour work using a `type` prop was causing `<Imgix />` to have mixed responsibilities. This was causing pecularities, such as needing to pass a `src` to a `<Imgix type='picture' />` even though it wasn't used. 
~- [ ] Add prop fall-through behaviour to `<Picture />`~
Review the changes to the tests.
> feat: refactor picture and source behaviour into different components

- README.md
- src/HOCs/shouldComponentUpdateHOC.js
- src/react-imgix.js
- test/integration/react-imgix.test.js
- test/unit/react-imgix.test.js
This PR allows the HTML attributes that are set by this library, such as `src` and `srcset`, to be re-mapped to other attributes. This allows developers to include other libraries, such as lazysizes, and use them in conjunction with this library. This follows the same pattern as what is used in imgix.js.
As I envision many people will want to use lazysizes with this library, I have added some integration tests to ensure that lazy loading and LQIP works with this library.
For the structure of the `attributeConfig` prop, please see the changes to the README.
Fixes #117 
- [N/A] If this is a big feature with breaking changes, consider [opening an issue][issues] to discuss first. This is completely up to you, but please keep in mind that your PR might not be accepted.
Review changes to the …
> feat: add HTML attribute configuration, enabling use of third-party libraries e.g. lazysizes

- renovate.json
This PR enables auto-merging of Renovate PRs under two circumstances:
- if the version update is a patch update, then automerge straight away
- if not a patch update, then wait for a PR comment with "@bors: r+", and then automerge
> chore(renovate): enable auto-merging

- src/react-imgix.js
- test/unit/react-imgix.test.js
This PR adds 4x and 5x dprs to the srcsets when using fixed dimension rendering. This allows images to look even better on new high-dpr devices.
- [N/A] If this is a big feature with breaking changes, consider [opening an issue][issues] to discuss first. This is completely up to you, but please keep in mind that your PR might not be accepted.
- [N/A] Update the readme
Check that tests are still passing.
> chore: add 4x and 5x dprs in srcset

- test/integration/react-imgix.test.jsx
The background mode PR slipped through with a few mistakes in the tests. This fixes them.
> test(background-mode): fix incorrect test and remove .only

- package.json
- src/react-imgix-bg.jsx
- test/integration/react-imgix.test.jsx
Any attempt to override the `fit` parameter when using a `Background` component will have no effect. Example + steps to reproduce can be found in #268.
Big thanks to @verbeeksteven for catching this and getting the ball rolling with #270.
Can be found under `test/integration/react-imgix.test.jsx`
> fix: ensure fit parameter will respect overriding value fixes #268

- CHANGELOG.md
- package-lock.json
- package.json
Release v8.6.0
* ensure `fit` parameter will respect overriding value, fixes [#268](https://github.com/imgix/react-imgix/issues/268) ([#311](https://github.com/imgix/react-imgix/issues/311)) ([15b0073](https://github.com/imgix/react-imgix/commit/15b0073)), fixes [#268](https://github.com/imgix/react-imgix/issues/268)
* append variable `q` parameters per `dpr` when rendering a fixed-size image ([#322](https://github.com/imgix/react-imgix/issues/322)) ([6594cea](https://github.com/imgix/react-imgix/commit/6594cea)), resolves [#129](https://github.com/imgix/react-imgix/issues/129)
> chore(release): 8.6.0

- package.json
Resolves #341 
There appears to be a regression in [react-measure](https://www.npmjs.com/package/react-measure) v2.2.6 that is causing `contentRect.bounds.width` and `contentRect.bounds.height` to return 0 in [react-imgix-bg](https://github.com/imgix/react-imgix/blob/15b0073f7b14679ebd6c43c1cf79bfb9c64b35c2/src/react-imgix-bg.jsx#L50). This causes the `<Background>` component to render without a `background-image` property. 
This PR will pin the version of react-measure to <2.2.6 in the meantime while we gather more information over at https://github.com/souporserious/react-measure/issues/137 
A comparison of react-measure [v2.2.6](https://codesandbox.io/s/3vv22zopj6) versus [v2.2.5](https://codesandbox.io/s/zk86221wq4)
> fix(deps): pin react-measure version to avoid regression

- README.md
This PR updates the codesandbox links in the README with forks that use the most recent version of react-imgix.
Resolves #389
> docs: update codesandbox links

- src/react-imgix.jsx
- src/targetWidths.js
- test/unit/react-imgix.test.jsx
Resolves #243 
Previously, `<Source>` elements were generated with a `srcSet` attribute defined in DPR mode by default, regardless of whether a width and/or height prop were passed in.
This PR modifies the `srcSet` generation in `<Source>` elements to mimic the same behavior as responsive images generated by the `<Imgix>` component. Now the `srcSet` will be generated with width descriptors by default unless either or both dimensions are defined.
In addition, this PR addresses two bugs:
- the <Source> component was appending the fallback `src` to the `srcSet` attribute
- the largest responsive width generated in a given `srcSet` was greater than the enforced `max_width`
> fix: render <Source> element as a fluid image by default

- src/constructUrl.js
I know this is getting old 😅 But I noticed a missed opportunity in `constructUrl` so here it is. I hope to focus on other parts of the code after this 😊
Combines `constructUrl` and `constructUrlFromParams`.
Since `constructUrl` was the only function using `constructUrlFromParams`.
Combining these functions removes one loop over params 🙌🏻
Profiling results in milliseconds. 100,000 iterations
|                                       | before   | after    | Change  |
|---------------------------------------|----------|----------|---------|
| responsive                            | 1960.634 | 1611.956 | -17.78% |
| responsive with fixed height          | 1743.363 | 1302.794 | -25.27% |
| responsive with aspect ratio          | 2781.415 | 1687.540 | -39.33% |
| fixed width …
> perf: constructUrl optimization

- src/constructUrl.js
- src/react-imgix.jsx
I replaced all instances of the object spread operator with `Object.assign`. The results are quite remarkable:
Benchmarks in ms. 100,000 iterations
|                                       | before   | after    | change  |
|---------------------------------------|----------|----------|---------|
| responsive                            | 1652.000 | 1104.215 | -33.16% |
| responsive with fixed height          | 1373.051 | 886.121  | -35.46% |
| responsive with aspect ratio          | 1862.155 | 1267.419 | -31.94% |
| fixed width                           | 1347.304 | 867.349  | -35.62% |
| fixed width with quality              | 1420.417 | 908.058  | -36.07% |
| fixed width with dpr quality disabled | 1305.567 | 872.474  | -33.17% |
| fixed width with aspect ratio         | 1326.964 | …
> perf: remove object spreading

- README.md
- src/react-imgix.jsx
- test/unit/react-imgix.test.jsx
This PR refactors how the `ReactImgix` component determines an image's aspect ratio, now using the [imgix aspect ratio parameter](https://blog.imgix.com/2019/07/17/aspect-ratio-parameter-makes-cropping-even-easier) `ar=` instead of appending a calculated height `h=` value based on the prop. This should yield overall better performance, code cleanliness, and bring the component more in line with the imgix API.
---------
**Demo**
Given the same component invocation, the URL constructed will be different but still render the same image.
```jsx
<Imgix
src="http://domain.imgix.net/image.jpg"
imgixParams={{ ar: "2:1" }}
/>
```
|        | Example srcset URL                                        |
|--------|-----------------------------------------------------------|
| Before | …
> refactor: use ar parameter instead of calculating aspect ratio

- package.json
- src/react-imgix.jsx
- test/unit/react-imgix.test.jsx
Fixes #475 
`findDOMNode` is deprecated in `StrictMode`. It's recommended against [in the official docs](https://reactjs.org/docs/react-dom.html#finddomnode), and if the functionality that it enables is required, `ref`s are a good way of addressing the problem.
This PR refactors away from `findDOMNode` towards `ref`s.
* Refactor `react-imgix` components to use `ref`s in favor of `findDOMNode`
* Refactor tests to use `mount` instead of `shallow`, since `shallow` doesn't create or use `ref`s
* Remove a test function that wasn't in use
See that the refactored tests are sane and passing.
I wasn't quite sure what sort of work this represented (fix/feature/chore). Please let me know if a different designation is more appropriate.
> chore: refactored from findDOMNode to refs

- README.md
- src/react-imgix.jsx
- test/unit/react-imgix.test.jsx
This PR removes the default `fit=crop` parameter from the ReactImgix component when building `src` and `srcset` attributes. This change will take effect in the next major release of react-imgix (v9.0.0).
**Background:** After some confusion arose regarding the differences between this project and imgix's API, we have decided it is best to remove `fit=crop` as a default parameter. This will realign the component behavior to match that of imgix's service in a way that users would expect when transitioning to this library.
The main difference this will yield for users is that they will now have to manually pass in the `fit=crop` parameter if so desired:
```jsx
<Imgix
src="https://assets.imgix.net/examples/pione.jpg"
sizes="100vw"
imgixParams={{ fit: "crop" }}
/>
```
Resolves #446
> fix: remove default fit parameter

- README.md
In preparation for release v9, the upgrade guide should provide users instructions on migrating to the next major version.
> docs: add upgrade guide section for 8.x to 9.0

- src/react-imgix.jsx
- test/unit/helpers/shallowUntilTarget.test.jsx
- test/unit/react-imgix.test.jsx
Fixes #494 
Refactoring work completed in #475 inadvertently introduced a regression where we are overwriting a `ref` passed via `htmlAttributes`. This PR better handles this situation while accounting for refs that are either passed as a callback or an object.
> fix: prevent overwriting htmlAttributes.ref

- README.md
Fixes a broken link to the [Contributors section](https://github.com/imgix/react-imgix#contributors-) in the table of contents. Apparently `✨`s aren't cool enough for markdown or something.
> docs: fix broken link to contributors section

- README.md
This PR serves as a follow up to #533, adding a few items that were missed:
- Adds the `` tag around the [Contributors](https://github.com/imgix/react-imgix#contributors-) section
- Adds a missing code block under the [Upgrade Guide](https://github.com/imgix/react-imgix#7x-to-80) section
> docs: add docs-ignore tag to contributors section

- README.md
This PR fixes #564 
When tested locally the contributors link in the README TOC only works when referenced as `#contributors-%e2%9c%a8` - this was created automatically by a vs code extension that I use. However, GitHub markdown won't work in the same way unless the encoded bit is excluded.
> docs: fix broken contributors link

- package.json
- src/react-imgix-bg.jsx
- test/unit/react-imgix.test.jsx
This PR changes the `hasDOMDimensions` to check for DOM `width` and `height`, rather than just the `top` — which will exist in cases where we still don't want to consider the DOM dimensions "usable".
This should fix #591 — which should, I imagine, stop Imgix from getting quite a few 400s
Please use the checklist that is most closely related to your PR _(you only need to use one checklist, and you can skip items that aren't applicable or don't make sense)_:
N/A:
The new unit test should be sufficient.
But if you want to test manually, too, then create a `<div style={{ width: 100, height: 0 }} /><Background /></div>` element
Related issue: #591
> fix(background): fortify `hasDOMDimensions` check for null height

- test/integration/react-imgix.test.jsx
This PR ensures that onLoad and onError handlers continue to work, since we've advertised this as a feature in the README.
There are no onLoad or onError handlers for Picture or Source elements in the HTML spec. Instead, the onLoad and onError handlers on the fallback image are triggered, no matter which source is chosen. So, this covers those use cases as well.
- [N/A] Update the readme
- [N/A] Update or add any necessary API documentation
Review the changes to the tests.
> test: htmlAttributes.onLoad and onError for Imgix component

- README.md
This PR updates the fixed image rendering doc to include `disableQualityByDPR`, which matches the rendered output.
> docs: correct example to include `disableQualityByDPR`

- .travis.yml
- config/karma/karmaConfig.js
This PR presents an attempt to mitigate the number of breaking TravisCI builds, specifically caused by Karma/BrowserStack timeouts. There are two main ways that a timeout can occur:
- **Within a single build**: One or more slow karma tests can delay the execution of subsequent tests, as there is a limit to the number of workers that can be run in parallel. If this delay occurs for long enough, the subsequent tests will not have enough time to complete prior to hitting the `captureTimeout` limit. We cannot configure the workers directly, but we can permit a higher timeout limit to give other tests ample time complete.
- **Across multiple builds**: All builds are run under the same BrowserStack account, which are subject to a non-configurable API rate limit of 800 requests per 5 minutes. If …
> ci(browserstack): reduce false-negative build failures

- README.md
Hello,
This tiny PR will fix : 
- 1 typo in `README.md`
Best! :robot:
> docs(readme): fix typo in README.md

- src/constructUrl.js
This follows up on a typo from #673.
> chore: fix license link to coursera

- package-lock.json
Output from `npm audit fix`:
> fixed 3392 of 3398 vulnerabilities in 2673 scanned packages
> chore(deps): sync with `npm audit fix`

- .travis.yml
- package.json
Adds [currently supported](https://nodejs.org/en/about/releases/) LTS node versions to CI.
TODO: remove EOL'd versions in a future major release
> ci: update supported node versions

- test/integration/react-imgix.test.jsx
- this pr fixes a bug where an `onError` callback didn't fire in one of the test suites. This is related to [an old firefox bug discussion](https://bugzilla.mozilla.org/show_bug.cgi?id=299138), where they establish that, per [HTML5 spec]( http://www.whatwg.org/specs/web-apps/current-work/#the-img-element):
> "Whether the image is fetched successfully or not (e.g. whether the response code was a 2xx code or equivalent) must be ignored when determining the image's type and whether it is a valid image."
Code:
```console
npm run test:browser
```
> test(react-imgix-test): change src url to valid url

- package.json
Looks like we are using double quotes rather than single quotes in this lib, which caused the semantic release step to fail.
I can't easily guarantee this works, will have to merge to main to see if it does.
> config(semantic): fix package version replacement

- package-lock.json
- package.json
- src/constants.js
- src/constructUrl.js
- src/react-imgix-bg.jsx
- src/react-imgix.jsx
- src/targetWidths.js
- test/integration/react-imgix.test.jsx
- test/unit/react-imgix.test.jsx
The purpose of this PR is to integrate `@imgix/js-core` into
`react-imgix`. First, `targetWidths` has been reimplemented in terms of
the js-core client. Second, `buildSrc` has been implemented in terms of
`ImgixClient.buildSrcSet`. Lastly, a bug fix was made for the
`Background` component.
Closes #763
> feat: integrate @imgix/js-core into react-imgix

- src/react-imgix-bg.jsx
- test/unit/should-component-update.test.js
The `shouldComponentUpdate` function is refactored outside of the `BackgroundImpl` component.
The refactored function, `__shouldComponentUpdate` takes `props` and `nextProps` as arguments. It returns `true` if the `children`, `imgixParams`, `contextRect`, `bounds`, `htmlAttributes`, or top-level `props` have changed. It returns `false` if the props have not changed.
The refactoring addresses an issue where: 
- changes to the children and imgixParams props were not detected
- the child components therefore did not re-render.
``` js
// src/react-imgix-bg.jsx  
// L15
export const __shouldComponentUpdate = (props, nextProps) => {
// ... choose which props to ignore and which ones to compare
const customizer = (oldProp, newProp, key) => {
// ... false if children prop has changed
if (key === …
```
> fix(789): ensure children passed to background component update 

- src/constants.js
The most recent release failed to bump the semver. This PR updates the semver from `9.1.2` to `9.1.3`.
> fix: constants out of sync with versions

- package-lock.json
I introduced a test-suite failure a few commits back when I bumped this manually after semantic release took "too long". It broke things. ~Hopefully~ this fixes things.
> build: bump package lock semver which is out of sync

- src/HOCs/imgixProvider.jsx
- test/unit/imgix-provider.test.jsx
This PR is part of a stack
| PR 	| Title 	| Merges Into 	|   	|
|----	|-------	|-------------	|---	|
|    1	|    [imgixProvider](https://github.com/imgix/react-imgix/pull/791) 👈🏼  	|        [luis/PE-828](https://github.com/imgix/react-imgix/tree/luis/PE-828)    	|   	|
|    2	|    [propsMerger](https://github.com/imgix/react-imgix/pull/790)     	|           #791  	|   	|
|    3	|    [wrapReactImgix](https://github.com/imgix/react-imgix/pull/792)    	|       #790      	|   	|
----
This commit creates a Provider component, `<ImgixProvider />`. The
component uses the `React.createContext()` API to create a props context
that can be modified and passed on to its child components. This is
useful as it allows for HOF that can format and combine imgixProps
before they're passed on `<ReactImgix …
> feat: create imgixProvider component

- src/HOCs/index.js
- src/constructUrl.js
- src/index.js
- src/react-imgix.jsx
- test/unit/imgix-provider.test.jsx
- test/unit/react-imgix.test.jsx
This PR uses the `mergePropsHOF` to wrap `ReactImgix` components with the ImgixContext. 
It also fixes a spelling mistake in the prop expander (b2fa08d).
- `mergePropsHOF` checks if ReactImgix is within an `ImgixContext`. 
- If it is, it combined the Provider and Child props and renders `ReactImgix` with the combined props. 
- If it isn't it renders `ReactImgix` with the props as-is.
https://user-images.githubusercontent.com/16711614/119424185-f97ffa00-bcd2-11eb-8722-729938995e84.mov
The prop expander (b2fa08d) fix should probably be removed form this PR and made into a standalone PR.
---
This PR is part of a stack
| PR 	| Title 	| Merges Into 	|   	|
|----	|-------	|-------------	|---	|
|    1	|    [imgixProvider](https://github.com/imgix/react-imgix/pull/791)  	| …
> feat: wrap ReactImgix in mergePropsHOF

- README.md
This PR updates `README.md` to include documentation for the new ✨ `<ImgixProvider>` HOC and `domain` prop.
> docs: update README to include ImgixProvider and domain info

- test/unit/find-closest.test.js
- test/unit/react-imgix.test.jsx
This PR fixes one and removes another test that had gotten out of sync with the code base.
In the case of `test/unit/react-imgix.test.jsx`, the removed test has been skipped for years and is assumed to be no longer relevant.
> chore: fix deprecated tests

- config/karma/karmaConfig.js
- package-lock.json
- package.json
This PR uses `browserlist-browserstack` to automatically pull in the latest BrowserStack capabilities for testing with Karma. Previously, the supported browsers had to be manually defined and updated. After this commit, we can request an updated array of capabilities from BrowserStack via their "Automate" API.
We use the result of that API call to filter the browserlist query results by what's actually supported by BrowserStack for Karma testing.
``` js
// this package will 
// 1) query browserlist 
// 2) query browserstack 
// 3) filter the result by what's supported
const mapBrowsersListToBrowserStackLaunchers = async () => {
return await browserList_browserStack
.default({
username: process.env.BROWSERSTACK_USERNAME,
accessKey: process.env.BROWSERSTACK_ACCESS_KEY,
browserslist: { …
```
> test: automatically update browserlist capabilities for karma testing

- README.md
- src/react-imgix.jsx
Right now the prop types do not include devicePixelRatios in srcSetOptions but it does work.
> docs: add devicePixelRatios to SHARED_IMGIX_AND_SOURCE_PROP_TYPES

- src/react-imgix.jsx
- test/unit/attributes.test.js
The `alt` attribute had to be set by making use of the `htmlAttributes` prop.
The `alt` attribute can be set using a top-level `alt` prop.
> feat: add alt top level prop

- README.md
- package-lock.json
- src/constructUrl.js
- src/react-imgix.jsx
- test/unit/encoding.test.js
This PR exposes the feature to disable path encoding, that was recently added to js-core. This behaviour is exposed through a new `disablePathEncoding` prop. Information about this new prop can be found in the README. 
Closes #815
> feat: allow path encoding to be disabled

- README.md
This warning was missing from the documentation
> docs: add info about invalidARFormat warning

- test/setupUnit.js
- test/unit/imgix-provider.test.jsx
- test/unit/react-imgix.test.jsx
Now the test output looks like this, rather than the mess it used to be:
> test: fixed all test warnings

- .github/worklows/add-issue-to-project.yml
This PR adds a GH Action to automatically add an issue tagged as `bug/need-triage` to the issues board.
> chore: add gh issue action

- .circleci/config.yml
Adds an additional test step to our CircleCI process to test successful builds.
Problems with builds can only be detected by CircleCI during the `deploy` step; this step only runs on `main` and prerelease branches. As a result, commits that break builds (included automated dependency updates by Renovate) in many cases might not be detected until after merge.
We now test for a successful `build` step on every branch.
> ci(build): add build test to circleci steps

- .circleci/config.yml
Adds an additional test step to our CircleCI process to test successful builds.
Problems with builds can only be detected by CircleCI during the `deploy` step; this step only runs on `main` and prerelease branches. As a result, commits that break builds (included automated dependency updates by Renovate) in many cases might not be detected until after merge.
We now test for a successful `build` step on every branch.
> ci: add build test to circleci steps

- src/react-imgix.jsx
- test/unit/react-imgix.test.jsx
(cherry picked from commit e58464c7038ef013b2d54c35aa086fbd9016d998)
related issue: #860 
related pr: #861
fixes issue HTML source tag failing the validation due to width/height presence in DOM
> fix: source width/height HTML validation

- src/react-imgix-bg.jsx
- test/unit/encoding.test.js
This PR fixes an issue where the `<Background />` component did not disable path encoding when the `disablePathEncoding` prop was set.
Related issue: #863
`disablePathEncoding` in `<Background>` did nothing.
Disable path encoding in `<Background>` does not over-encode the filepath.
```bash
expect(received).toMatch(expected)
Expected substring: "url(https://sdk-test.imgix.net/%26%24%2B%2C%3A%3B%3D%3F%40%23.jpg?fit=crop&w=100&h=100&dpr=1)"
Received string:    "url(https://sdk-test.imgix.net/%2526%2524%252B%252C%253A%253B%253D%253F%2540%2523.jpg?fit=crop&w=100&h=100&dpr=1)"
```
> fix(background): disable path encoding

- README.md
- src/react-imgix.jsx
- test/unit/react-imgix.test.jsx
Before this PR there was no way to allow width and height attributes through to the `img` element while still using a srcset with width descriptors rather than resolution descriptors. Telling the browser the intrinsic dimensions and therefore the aspect ratio is important to avoid layout shift.
After this PR width and height are allowed through via the `htmlAttributes` prop, without affecting the logic Imgix takes to decide on srcset type.
To test, do something like
`<Imgix src="..." sizes="50vw" htmlAttributes={{width: 400, height: 200}} />` and the output should include the width and height, such as `<img src="..." srcset="..." sizes="50vw" width="400" height="200" />`. Now the browser knows the aspect before any image data is loaded, so it can reserve the correct amount of space.
This …
> Allow width and height to be passed through htmlAttributes

- README.md
- src/index.js
This PR adds the `"use client"` directive to the components index file.
Before this PR, consumer who didn't add `"use client"` in a file or wrapper where `<Imgix>` was used would see a build error in NextJs 13.
After this PR, consumers no longer see this error, and can use `<Imgix>`, `<Picture>`, and `<Background>` as client components, and, critically, as children of server only components.
> feat: add use client directive to index

- .circleci/config.yml
- src/react-imgix-bg.jsx
- test/unit/imgix-provider.test.jsx
This PR address [issue](https://github.com/imgix/react-imgix/issues/931): Background component doesn't utilize ImgixProvider's domain parameter
- `mergeComponentPropsHOF` and `processPropsHOF` now wrap `withContentRect("bounds")(BackgroundImpl)`
**BEFORE:**
Imgix domain prop was not being passed to Background component from ImgixProvider
```js
<ImgixProvider domain={IMGIX_DOMAIN}>
<Imgix
src="image.jpg"
width={100}
/> {/* The Imgix component successfully uses the domain from the Provider */}
<Background src="image.png" className="blog-title">
<h2>Blog Title</h2>
</Background> {/* The Background component fails to utilize the domain from the Provider */}
</ImgixProvider>
```
**AFTER:**
Imgix domain prop can be access by Background component from ImgixProvider
It takes a little set up to …
> [PE-4862] Updates background component to merge props

- .circleci/config.yml
- README.md
Correct readme instructions to use "&" instead of "&amp;" to chain parameters.
Same for output HTML code snippets.
> fix(readme):remove html encoding from parameter strings

- README.md
Clarifies casing around Imgix by formatting it as a component. Also adds links to our rendering API.
```
When width and height are specified, Imgix will give the image a srcset with resolution descriptors.
```
```
When width and height are specified, `<Imgix>` will give the image a srcset with resolution descriptors.
```
> SUPPORT-531 : Clarifies `Imgix` casing

- src/constructUrl.js
Per https://github.com/imgix/react-imgix/issues/949, disablePathEncoding parameter doesn't do anything right now.
disablePathEncoding: true will still encode the path
disablePathEncoding: true will not encode the path
> fix: forward disablePathEncoding bool to consctructUrl call

- .circleci/config.yml
semantic-release doesn't complete right now.
deploy step abruptly stops after this line log:
`(node:399) [DEP0174] DeprecationWarning: Calling promisify on a function that returns a Promise is likely a mistake.`
> chore: update Node.js version in CircleCI config

- README.md
- src/react-imgix.jsx
- test/unit/react-imgix.test.jsx
This PR makes two minor changes to `react-imgix`:
1) It updates the documentation to prioritize browser-level lazy loading using the loading="lazy" attribute. This approach is [well-supported by browsers](https://caniuse.com/loading-lazy-attr), and removes the need for external JavaScript libraries.
2) It adds a small piece of additional functionality to optimize the sizes attribute by prepending `"auto, "` to the `sizes` attribute when `loading="lazy"` is used, and the image does not have a height and width specified. The latter condition is because when both height and width are specified, the image is treated as fixed size, and gets a DPR-dependent srcset, which does not benefit from `sizes="auto"`. 
The `sizes="auto"` optimization allows supporting browsers to automatically select the …
> feat: add sizes=auto fallback to lazy-loaded images

- README.md
- src/config.js
- src/react-imgix.jsx
- test/integration/react-imgix.test.jsx
This PR adds two new runtime warnings, which are only enabled in development environments, and which can be turned off with the existing `config.warnings` mechanism. The warnings are:
**oversizedImage**: This warning triggers when an image is finished loading, if it's detected that the rendered image is more than 500px smaller in either dimension that the image's intrinsic size. Oversized images are a common contributor to lower LCP scores.
**lazyLCP**: This triggers at runtime when the `performanceObserver` API identifies an image as potentially being the [LCP element ](https://web.dev/articles/lcp), and that image also has the `loading="lazy"` attribute. This combination is terrible for LCP, and is an easy fix, so I expect this warning to show up infrequently but be useful when it does. …
> feat: add performance warnings
