src/index.js
Change child props behaviour to only pass down props not used, not every prop
- as a bonus, we no longer have to delete child props!
=> Better child props

package.json, src/index.js, src/index.test.js, src/support.js
Hey @frederickfogerty, it'd be great if you could get take a quick peek at this. :smile:
=> Ensure all query keys + B64 variants are encoded.

src/index.js, src/index.test.js
=> Rename `aggresiveLoad` to `aggressiveLoad`.

README.md, src/index.js, src/index.test.js
=> introduces imgProps prop to handle html attributes

src/index.js, src/index.test.js
See https://github.com/imgix/react-imgix/issues/49 for the full context.
I've added some additional tests and they are all passing but I've not actually tried running the built code in a real project yet so I can't be sure there aren't any regressions.
=> Avoid blank background urls and src attributes

.travis.yml
To be honest, we should be doing browser testing with Chrome if we're really serious about this
=> Update node versions supported

README.md, package.json, src/array-findindex.js, src/index.js, src/index.test.js
first pass, still testing it out in our app. 
Closes #55
=> Picture element

README.md
=> Update readme to include customParams example, closes #75

package.json, src/index.js, src/support.js, yarn.lock
this fixes the child type comparison which could result in multiple `<ReactImgix type='img' />` elements added to a `<ReactImgix type='picture'>` when minification was in use. 
also updated deps.
=> Fix child bugs

src/index.js
Referencing issue:
https://github.com/imgix/react-imgix/issues/118
=> Add single quotes to background url.

.travis.yml
=> chore: update travis node to version 9

README.md, src/index.js
Also add prop types for height/width/defaultHeight/defaultWidth
=> Document default height/width props

README.md
This PR helps users of this project find combinations of props to use in certain situation. This helps solve or prevent some issues such as #139, #56, and #127. The examples also include a REPL (provided by CodeSandbox) where it makes sense.
This closes #140
=> docs(examples): add examples of types of usage to README

renovate.json
This PR updates the automerge config to disable pr-comment merging, and to merge patch versions and devDependencies automatically.
=> chore(renovate): update automerge config

.travis.yml
This PR updates the Travis node version to follow the "10" flag
=> chore: update travis node version to 10.x

.github/pull_request_template.md
`pull_request_template.md` documented the incorrect command for running prettier locally. This PR fixes the doc to reflect the actual command that should be used.
=> docs: fix prettier script command in pull_request_template.md

src/HOCs/deprecatePropsHOC.jsx, src/HOCs/shouldComponentUpdateHOC.jsx, test/integration/react-imgix.test.jsx, test/unit/react-imgix.test.jsx
Syncing the repo with some prettier changes I noticed locally.
=> style: sync with prettier

package-lock.json
Syncs compatible updates made by `npm audit fix` to resolve vulnerable dependencies.
=> chore(deps): run audit fix for repo

README.md
Hello, and thanks for contributing to react-imgix! 🎉🙌
**Before submitting a pull request,** please make sure the following is done:
1.  Fork [the repository](https://github.com/imgix/react-imgix) and create your branch from `master`.
2.  Run `npm install` in the repository root.
3.  If you've fixed a bug or added code that should be tested, add tests!
4.  Ensure the test suite passes (`npm run test`). Tip: `npm run --watch` is helpful in development.
5.  Format your code with [prettier](https://github.com/prettier/prettier) (`npm run pretty`). Don't worry too much if you haven't done this, we have a bot that will do this for you when you submit a PR.
6.  Fill out the template below and delete everything above the line.
**Learn more about contributing:** …
=> docs: update "Picture" example with correct width declaration

README.md
This PR updates the README to elaborate on the more advanced usages of this library, and to try increase the visibility of the htmlAttributes field.
This PR is a bit messy because I re-ordered some of the documentation to better distinguish between basic and advanced use cases.
=> docs: improve advanced usage doc

README.md
'picture' is missing when rendered
Hello, and thanks for contributing to react-imgix! 🎉🙌
**Before submitting a pull request,** please make sure the following is done:
1.  Fork [the repository](https://github.com/imgix/react-imgix) and create your branch from `master`.
2.  Run `npm install` in the repository root.
3.  If you've fixed a bug or added code that should be tested, add tests!
4.  Ensure the test suite passes (`npm run test`). Tip: `npm run --watch` is helpful in development.
5.  Format your code with [prettier](https://github.com/prettier/prettier) (`npm run pretty`). Don't worry too much if you haven't done this, we have a bot that will do this for you when you submit a PR.
6.  Fill out the template below and delete everything above the line.
**Learn more about contributing:** …
=> docs: fix typo in 'Picture Support' section

CONTRIBUTING.md, README.md, src/constructUrl.js
This PR changes any references from the master branch to the main branch, now that it is the default.
=> chore: change refs of master to main

.github/pull_request_template.md
This PR follows up on the branch changes with some changes that were missed initially.
=> chore: update some more refs to master

package.json
ssia, slight mis-config causing release to fail
=> config(semantic): fix version bump

README.md
=> docs: update fluid codesandbox link

src/HOFs/propMerger.js, src/react-imgix.jsx, test/unit/react-imgix.test.jsx
This was causing a React error during render
=> fix: bug where _inPicture would be set on <img>'s that were children of <Picture>

src/react-imgix.jsx
=> chore: remove unused variable

package-lock.json, package.json
=> chore(deps): move prop-types to dependencies

.circleci/config.yml, package-lock.json, package.json
=> fix: add support for react 18

.circleci/config.yml, CHANGELOG.md, package-lock.json, package.json, src/constants.js
=> chore: merge `beta` into `main`

README.md
=> docs: update ci badge and remove deps badge

.circleci/config.yml
- use `current` in favor of `stable`
- always use `openssl-legacy-provider`
- use `current` in favor of `17.9`
=> ci: node compat fixes

.circleci/config.yml, package-lock.json, package.json
Updates deps and CircleCI orbs to fix breaking CI task runs.
Before this PR:
- CircleCI tests failed to run because of flaky browsers orb
- CircleCI release step failed to run because of replace plugin node version esm/require syntax error
After this PR:
- CircleCI runs succeed
=> ci: fix breaking circle-ci browsers orb & release step
